# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'etc'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # public network. FIXME: hardcoded bridge name: br0
  config.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge"

  # LIBVIRT provider BEGIN
  config.vm.provider :libvirt do |libvirt|
    # libvirt.storage_pool_name = 'default'
    libvirt.driver = "kvm"
    libvirt.memory = 2048
    libvirt.cpus = 1
    libvirt.graphics_ip = '0.0.0.0'
    # libvirt.machine_type = 'pc'
    libvirt.machine_type = 'q35'
    libvirt.emulator_path = '/usr/bin/qemu-system-x86_64'
    libvirt.default_prefix = 'jenkins'
  end
  # LIBVIRT provider END
  
  # now, create VMs
  vm_name = ENV['VM_NAME'] || (Dir.getwd.split('/')[-1] == 'builder' ? 'builder0' : 'master')
  config.vm.define vm_name do |domain|
    domain.vm.hostname = "jenkins-#{vm_name}"
    domain.vm.provider :libvirt do |libvirt|
    end
    domain.vm.network "forwarded_port", guest: 80, host: 8080
    script = (vm_name == 'master') ? "provision_master.sh" : "provision_builder.sh"
    domain.vm.provision "shell", :path => script, :privileged => true
  end  # end of :master domain
end
